// angular-env/src/app/pages/products/products.component.ts
// src/app/pages/products/products.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-products',
  templateUrl: './products.component.html',
  standalone: true
})
export class ProductsComponent implements OnInit {
  products: any[] = [];

  constructor(private http: HttpClient) {}

  ngOnInit(): void {
    this.http
      .get('https://jsonplaceholder.typicode.com/posts')
      .subscribe((data: any) => {
        this.products = data.slice(0, 10);
      });
  }
}

<!-- src/app/pages/products/products.component.html -->
<main>
  <h2>Unsere Produkte</h2>
  <ul>
    <li *ngFor="let product of products">
      {{ product.title }}
    </li>
  </ul>
</main>

// react-env/src/pages/Products.js
// src/pages/Products.js
import React, { useState, useEffect } from 'react';

function Products() {
    const [products, setProducts] = useState([]);

    useEffect(() => {
        fetch('https://jsonplaceholder.typicode.com/posts') // Beispiel-API
            .then(response => response.json())
            .then(data => setProducts(data));
    }, []);

    return (
        <main>
            <h2>Unsere Produkte</h2>
            <ul>
                {products.slice(0, 10).map(product => (
                    <li key={product.id}>{product.title}</li>
                ))}
            </ul>
        </main>
    );
}

export default Products;
