// angular-env/src/app/components/header/header.component.ts
import { Component } from '@angular/core';
import {NavigationComponent} from "../navigation/navigation.component";

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [
    NavigationComponent
  ],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent {

}

<!-- src/app/components/header/header.component.html -->
<header>
  <h1>Test-Webanwendung</h1>
  <app-navigation></app-navigation>
</header>

// vue-env/src/components/Header.vue
<!-- src/components/Header.vue -->
<template>
  <header>
    <h1>Test-Webanwendung</h1>
    <Navigation />
  </header>
</template>

<script>
import Navigation from './Navigation.vue';

export default {
  name: 'HeaderComponent',
  components: {
    Navigation,
  },
};
</script>

<style scoped>
/* Optionales Styling */
</style>
