// react-env/src/components/Navigation.js
// src/components/Navigation.js
import React from 'react';
import { Link } from 'react-router-dom';

function Navigation() {
    return (
        <nav>
            <ul>
                <li><Link to="/">Startseite</Link></li>
                <li><Link to="/about">Über Uns</Link></li>
                <li><Link to="/products">Produkte</Link></li>
            </ul>
        </nav>
    );
}

export default Navigation;

// vue-env/src/components/Navigation.vue
<!-- src/components/Navigation.vue -->
<template>
  <nav>
    <ul>
      <li><router-link to="/">Startseite</router-link></li>
      <li><router-link to="/about">Über Uns</router-link></li>
      <li><router-link to="/products">Produkte</router-link></li>
    </ul>
  </nav>
</template>

<script>
export default {
  name: 'NavigationComponent',
};
</script>

<style scoped>
/* Optionales Styling */
</style>
